### ISSUE TITLE
Trial of the Gods with Hestia and Artemis is broken

### ISSUE THREAD

**Issue by Fly0DB** [AlexKage69/OlympusExtra#100]
I took first Hestia, then Artemis. The phrase of Artemis appeared, but there was no fight, the boon of Artemis became immediately available.
I got only 1 trial with Hestia now, so maybe other trials with her are broken too.

**Comment by phypoh** [comment]
This is intended! In a Trial of the Gods, there is a possibility of a "forgiveness" scene, where the offended god forgives you even though you picked Hestia, just because she's nice! If you read Artemis's lines, she would've said "Look, I also appreciate Hestia, but that's no reason not to pick me. I mean... alright, I'll let it go this time. Don't get used to it."
