### ISSUE TITLE
Trap Jar does not apply jealousy

### ISSUE THREAD

**Issue by phypoh** [AlexKage69/OlympusExtra#179]
Also can we reduce the cooldown on the trap jar by 1 second for each? It feels somewhat clunky
Also does trap jar count as trap damage?

**Comment by AlexKage69** [comment]
So lower cooldown makes the trap jar too powerful since the map is just filled with Jars that damage enemies. The way you use it is by calculating when to dash instead of dashing like crazy. I'll lower it from 3->2.5. If you want more jar you need the artemis duo which gives you 2.5/3 kind of jars since you get 3 charges. We could also improve the loading Icon on the side. And yes, Trap jar is a Trap Damage and gets boosted by trap damage boost.
